#! /bin/bash
# Give desktop time to start
sleep 10

export WINEPREFIX=/config/.wine
export WINEARCH=win64
export HOME=/config
export DISPLAY=:1

cd /config
nohup wine OutlookGoogleCalendarSync.exe &>/config/ogcs.log &