---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Discord Notifications

on:
  issues:
    types: ["opened"]
  pull_request:
    types: ["opened"]

permissions:
  contents: read

jobs:
  notify:
    if: ${{ github.actor != 'sticky-gecko[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        uses: sarisia/actions-status-discord@5ddd3b114a98457dd80a39b2f00b6a998cd69008 # v1.15.3
        with:
          color: "0x0275F1"
          description: |
            ${{ github.event.issue.title || github.event.pull_request.title }}
          nodetail: true
          title: New ${{ github.event.issue.pull_request && 'pull request' || 'issue' }} in ${{ github.repository }} by ${{ github.event.issue.user.login || github.event.pull_request.user.login }}
          username: GitHub Actions
          url: ${{ github.server_url }}/${{ github.repository }}/${{ github.event.issue.pull_request && 'pull' || 'issues' }}/${{ github.event.issue.number || github.event.pull_request.number }}
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
