---
name: Release

on:
  push:
    branches: ["master"]
    paths: ["apps/**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  changed-apps:
    name: Get Changed Apps
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.apps.outputs.apps }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine changed files
        uses: JJGadgets/tj-actions-changed-files@9200e69727eb73eb060652b19946b8a2fdfb654b
        id: changed-dirs
        with:
          dir_names: true
          dir_names_max_depth: "1"
          path: apps

      - name: Extract App values
        id: apps
        working-directory: apps
        run: |
          apps=$(printf "%s/metadata.yaml\n" ${{ steps.changed-dirs.outputs.all_changed_and_modified_files }})
          apps=$(yq eval-all --indent=0 --output-format=json "[.]" ${apps})
          echo "apps=${apps}" >> $GITHUB_OUTPUT

  build:
    needs: changed-apps
    name: Build ${{ matrix.app.name }} (${{ matrix.platform }})
    runs-on: ${{ matrix.platform == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    strategy:
      matrix:
        app: ${{ fromJSON(needs.changed-apps.outputs.apps) }}
        platform: ["amd64", "arm64"]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.app.name }}
          tags: |
            type=raw,value=${{ github.sha }}-${{ matrix.platform }}
          flavor: |
            latest=false

      - name: Build Image
        uses: docker/build-push-action@v6
        id: build
        with:
          build-args: |-
            VENDOR=${{ github.repository_owner }}
            VERSION=${{ matrix.app.version }}
            REVISION=${{ github.sha }}
          context: ./apps/${{ matrix.app.name }}
          platforms: linux/${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          push: true

  merge:
    name: Merge ${{ matrix.app.name }}
    runs-on: ubuntu-latest
    needs: ["changed-apps", "build"]
    if: ${{ !cancelled() }}
    strategy:
      matrix:
        app: ${{ fromJSON(needs.changed-apps.outputs.apps) }}
      fail-fast: false
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.app.name }}
          tags: |
            type=match,pattern=^(\d+(\.\d+)?(\.\d+)?(\.\d+)?),value=${{ matrix.app.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ matrix.app.version }},enable=${{ matrix.app.semver }}
            type=semver,pattern={{major}},value=${{ matrix.app.version }},enable=${{ matrix.app.semver }}
            type=raw,value=rolling
          flavor: |
            latest=false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Push Images
        id: push
        uses: Noelware/docker-manifest-action@master
        with:
          inputs: ${{ join(fromJSON(steps.meta.outputs.json).tags, ',') }}
          images: >-
            ghcr.io/${{ github.repository_owner }}/${{ matrix.app.name }}:${{ github.sha }}-amd64,
            ghcr.io/${{ github.repository_owner }}/${{ matrix.app.name }}:${{ github.sha }}-arm64
          push: true

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign Image
        run: |
          digest=$(echo "${{ steps.push.outputs.images }}" | cut -d "," -f1 | cut -d "@" -f2)
          cosign sign --yes ghcr.io/${{ github.repository_owner }}/${{ matrix.app.name }}@${digest}

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ghcr.io/${{ github.repository_owner }}/${{ matrix.app.name }}:${{ matrix.app.version }}
