---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Retry Release

on:
  schedule:
    - cron: "30 5 * * *"
  workflow_dispatch:

jobs:
  repository:
    name: Get Repository Apps
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.repository.outputs.apps }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Apps
        uses: ./.github/actions/app-inventory
        id: repository

  retry:
    if: ${{ needs.repository.outputs.apps != '[]' }}
    name: Retry Release
    runs-on: ubuntu-latest
    needs: repository
    strategy:
      matrix:
        app: ${{ fromJSON(needs.repository.outputs.apps) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Vars
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        id: vars
        with:
          script: |
            core.setOutput('repository-owner', '${{ github.repository_owner }}'.toLowerCase());

      - name: Generate Token
        uses: actions/create-github-app-token@af35edadc00be37caa72ed9f3e6d5f7801bfdf09 # v1.11.7
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # v3.8.1

      - name: Install regctl
        uses: regclient/actions/regctl-installer@main

      - name: Get App Version
        id: app-version
        working-directory: ./apps/${{ matrix.app }}
        run: |
          VERSION=$(docker buildx bake image-all --print | jq --raw-output --compact-output '.target."image-all".args.VERSION')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Get Container Registry Version
        id: registry
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          if ! version=$(regctl image inspect ghcr.io/${{ steps.vars.outputs.repository-owner }}/${{ matrix.app }}:rolling \
              | jq --raw-output '.config.Labels["org.opencontainers.image.version"]' 2>/dev/null) || [[ -z "${version}" ]];
          then
              echo "Failed to get registry version for ${{ matrix.app }}"
              exit 1
          fi
          echo "version=${version}" >> $GITHUB_OUTPUT

      - if: ${{ steps.app-version.outputs.version != steps.registry.outputs.version }}
        name: Retry Release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh workflow run release.yaml \
              --repo ${{ github.repository }} \
              -f app=${{ matrix.app }} \
              -f release=true

          {
              echo '## Retrying Release'
              echo
              echo '| Container Name | Actual Version | Expected Version |'
              echo '|----------------|------------------|----------------|'
              echo '| `${{ matrix.app }}` | `${{ steps.registry.outputs.version }}` | `${{ steps.app-version.outputs.version }}` |'
          } >> $GITHUB_STEP_SUMMARY
