---
name: Vulnerability Scan

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

jobs:
  repository:
    name: Get Repository Apps
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.repository.outputs.apps }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Output
        id: repository
        run: echo "apps=$(yq eval-all --indent 0 --output-format json '[.]' apps/*/metadata.yaml)" >> $GITHUB_OUTPUT

  database:
    name: Download Grype Database
    runs-on: ubuntu-latest
    steps:
      - name: Download Grype Database
        uses: anchore/scan-action/download-grype@7c05671ae9be166aeb155bad2d7df9121823df32 # v6.1.0
        id: grype
        with:
          cache-db: true

  vulnerability-scan:
    needs: ["repository", "database"]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        apps: ${{ fromJSON(needs.repository.outputs.apps) }}
      max-parallel: 4
      fail-fast: false
    permissions:
      security-events: write
    steps:
      - name: Scan
        uses: anchore/scan-action@7c05671ae9be166aeb155bad2d7df9121823df32 # v6.1.0
        id: scan
        with:
          cache-db: true
          fail-build: false
          image: ghcr.io/${{ github.repository_owner }}/${{ matrix.apps.name }}:rolling

      - name: Upload
        uses: github/codeql-action/upload-sarif@5f8171a638ada777af81d42b55959a643bb29017 # v3.28.12
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
